include: package:lints/recommended.yaml

linter:
  rules:
    # Error rules
    avoid_empty_else: true
    avoid_print: false  # We use print for logging
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    valid_regexps: true
    
    # Style rules
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_types: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    null_closures: true
    one_member_abstracts: false
    package_api_docs: false
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    use_rethrow_when_possible: true

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
  
  errors:
    # Treat missing required params as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
    # Allow TODOs
    todo: ignore
